package main

import (
	"encoding/json"
	"fmt"
	"go/format"
	"io"
	"math"
	"net/http"
	"net/url"
	"os"
	"path/filepath"
	"strings"
	"time"

	"stationnum2omap/internal/locator"
)

const (
	stepMeters = 100
	batchSize  = 80
	endpoint   = "https://api.opentopodata.org/v1/srtm30m"
)

type sample struct {
	meter     int
	latitude  float64
	longitude float64
	elevation int
}

type apiResponse struct {
	Status  string `json:"status"`
	Results []struct {
		Elevation *float64 `json:"elevation"`
	} `json:"results"`
}

func main() {
	client := &http.Client{Timeout: 45 * time.Second}
	var source strings.Builder
	source.WriteString("// Code generated by go run ./tools/generate_elevation_data; DO NOT EDIT.\n")
	source.WriteString("// SRTM 30 m terrain elevations from https://www.opentopodata.org/datasets/srtm/ (2026-09-28).\n")
	source.WriteString("package locator\n\nvar elevationProfiles = map[string][]elevationSample{\n")
	var totalArea, totalLength float64
	requests := 0
	for _, segment := range locator.RouteCatalog() {
		if segment.Brigade != "韵家口大队" {
			continue
		}
		samples := make([]sample, 0, (segment.EndMeter-segment.StartMeter)/stepMeters+2)
		for meter := segment.StartMeter; ; meter += stepMeters {
			if meter > segment.EndMeter {
				meter = segment.EndMeter
			}
			station := fmt.Sprintf("%s K%d+%03d", segment.Code, meter/1000, meter%1000)
			point, err := locator.LocateForSegment(segment.ID, station)
			if err != nil {
				fail("locate %s: %v", station, err)
			}
			samples = append(samples, sample{meter: meter, latitude: point.Latitude, longitude: point.Longitude})
			if meter == segment.EndMeter {
				break
			}
		}
		for start := 0; start < len(samples); start += batchSize {
			end := start + batchSize
			if end > len(samples) {
				end = len(samples)
			}
			if requests > 0 {
				time.Sleep(1100 * time.Millisecond)
			}
			if err := fillElevations(client, samples[start:end]); err != nil {
				fail("%s samples %d-%d: %v", segment.ID, start, end, err)
			}
			requests++
		}
		fmt.Fprintf(&source, "\t%q: {\n", segment.ID)
		var area float64
		for index, item := range samples {
			fmt.Fprintf(&source, "\t\t{%d, %d},\n", item.meter, item.elevation)
			if index > 0 {
				previous := samples[index-1]
				area += float64(item.elevation+previous.elevation) * float64(item.meter-previous.meter) / 2
			}
		}
		source.WriteString("\t},\n")
		length := float64(segment.EndMeter - segment.StartMeter)
		fmt.Printf("%s %s-%s: %d samples, %.1f m mean\n", segment.ID, segment.Start, segment.End, len(samples), area/length)
		totalArea += area
		totalLength += length
	}
	source.WriteString("}\n")
	formatted, err := format.Source([]byte(source.String()))
	if err != nil {
		fail("format generated data: %v", err)
	}
	path := filepath.Join("internal", "locator", "elevation_generated.go")
	if err := os.WriteFile(path, formatted, 0o644); err != nil {
		fail("write %s: %v", path, err)
	}
	fmt.Printf("韵家口大队全段里程加权平均: %.1f m (%d requests)\n", totalArea/totalLength, requests)
}

func fillElevations(client *http.Client, samples []sample) error {
	locations := make([]string, len(samples))
	for index, item := range samples {
		locations[index] = fmt.Sprintf("%.7f,%.7f", item.latitude, item.longitude)
	}
	query := url.Values{"locations": {strings.Join(locations, "|")}, "interpolation": {"bilinear"}}
	var lastErr error
	for attempt := 0; attempt < 3; attempt++ {
		if attempt > 0 {
			time.Sleep(time.Duration(attempt*2) * time.Second)
		}
		response, err := client.Get(endpoint + "?" + query.Encode())
		if err != nil {
			lastErr = err
			continue
		}
		body, err := io.ReadAll(io.LimitReader(response.Body, 1<<20))
		response.Body.Close()
		if err != nil {
			lastErr = err
			continue
		}
		if response.StatusCode != http.StatusOK {
			lastErr = fmt.Errorf("HTTP %d: %s", response.StatusCode, strings.TrimSpace(string(body)))
			continue
		}
		var result apiResponse
		if err := json.Unmarshal(body, &result); err != nil {
			return err
		}
		if result.Status != "OK" || len(result.Results) != len(samples) {
			return fmt.Errorf("unexpected response status %q or sample count %d", result.Status, len(result.Results))
		}
		for index, item := range result.Results {
			if item.Elevation == nil || math.IsNaN(*item.Elevation) || math.IsInf(*item.Elevation, 0) {
				return fmt.Errorf("missing or invalid elevation at sample %d", index)
			}
			samples[index].elevation = int(math.Round(*item.Elevation))
		}
		return nil
	}
	return lastErr
}

func fail(format string, args ...any) {
	fmt.Fprintf(os.Stderr, format+"\n", args...)
	os.Exit(1)
}
