// Command generate_network_data embeds public motorway, trunk and primary
// geometries used by the local, station-centred map. It reads the saved
// Overpass snapshot instead of making builds depend on the network.
package main

import (
	"encoding/json"
	"fmt"
	"os"
	"sort"
	"strconv"
	"strings"
)

type osmPoint struct {
	Lat float64 `json:"lat"`
	Lon float64 `json:"lon"`
}

type osmWay struct {
	Type     string            `json:"type"`
	ID       int64             `json:"id"`
	Tags     map[string]string `json:"tags"`
	Geometry []osmPoint        `json:"geometry"`
}

type osmResponse struct {
	Elements []osmWay `json:"elements"`
}

func main() {
	files := []string{
		"data/osm-xining-highways-2026-09-05.json",
		"data/osm-route-corridors-2026-09-05.json",
		"data/osm-route-relations-full-2026-09-05.json",
		"data/osm-s104-corridor-classes-2026-09-05.json",
	}
	ways := make(map[int64]osmWay)
	for _, file := range files {
		input, err := os.ReadFile(file)
		if err != nil {
			panic(err)
		}
		var response osmResponse
		if err := json.Unmarshal(input, &response); err != nil {
			panic(err)
		}
		for _, way := range response.Elements {
			if way.Type == "way" {
				ways[way.ID] = way
			}
		}
	}

	var out strings.Builder
	out.WriteString("// Code generated by tools/generate_network_data; DO NOT EDIT.\n")
	out.WriteString("// Source: OpenStreetMap public highway geometries, downloaded 2026-09-04/09-05.\n")
	out.WriteString("package locator\n\nvar embeddedRoadNetwork = []roadGeometry{\n")
	count := 0
	ids := make([]int64, 0, len(ways))
	for id := range ways {
		ids = append(ids, id)
	}
	sort.Slice(ids, func(i, j int) bool { return ids[i] < ids[j] })
	for _, id := range ids {
		way := ways[id]
		if way.Type != "way" || len(way.Geometry) < 2 {
			continue
		}
		highway := way.Tags["highway"]
		if highway != "motorway" && highway != "motorway_link" && highway != "trunk" && highway != "trunk_link" && highway != "primary" && highway != "primary_link" {
			continue
		}
		fmt.Fprintf(&out, "{OSMID: %d, Highway: %q, Ref: %q, Name: %q, Lanes: %d, OneWay: %t, Points: []point{\n",
			way.ID, highway, way.Tags["ref"], way.Tags["name"], lanes(way.Tags["lanes"], highway), way.Tags["oneway"] != "no")
		for _, point := range way.Geometry {
			fmt.Fprintf(&out, "{Lat: %.7f, Lon: %.7f},\n", point.Lat, point.Lon)
		}
		out.WriteString("}},\n")
		count++
	}
	out.WriteString("}\n")
	if err := os.WriteFile("internal/locator/network_generated.go", []byte(out.String()), 0644); err != nil {
		panic(err)
	}
	fmt.Printf("embedded %d motorway and motorway_link ways\n", count)
}

func lanes(value, highway string) int {
	parsed, err := strconv.Atoi(value)
	if err == nil && parsed > 0 && parsed < 9 {
		return parsed
	}
	if strings.HasSuffix(highway, "_link") {
		return 1
	}
	return 2
}
