// Command generate_network_data embeds the public motorway and motorway_link
// geometries used by the local, station-centred map. It reads the saved
// Overpass snapshot instead of making builds depend on the network.
package main

import (
	"encoding/json"
	"fmt"
	"os"
	"strconv"
	"strings"
)

type osmPoint struct {
	Lat float64 `json:"lat"`
	Lon float64 `json:"lon"`
}

type osmWay struct {
	Type     string            `json:"type"`
	ID       int64             `json:"id"`
	Tags     map[string]string `json:"tags"`
	Geometry []osmPoint        `json:"geometry"`
}

type osmResponse struct {
	Elements []osmWay `json:"elements"`
}

func main() {
	input, err := os.ReadFile("data/osm-qinghai-motorways-2026-09-04.json")
	if err != nil {
		panic(err)
	}
	var response osmResponse
	if err := json.Unmarshal(input, &response); err != nil {
		panic(err)
	}

	var out strings.Builder
	out.WriteString("// Code generated by tools/generate_network_data; DO NOT EDIT.\n")
	out.WriteString("// Source: OpenStreetMap motorway and motorway_link ways, downloaded 2026-09-04.\n")
	out.WriteString("package locator\n\nvar embeddedRoadNetwork = []roadGeometry{\n")
	count := 0
	for _, way := range response.Elements {
		if way.Type != "way" || len(way.Geometry) < 2 {
			continue
		}
		highway := way.Tags["highway"]
		if highway != "motorway" && highway != "motorway_link" {
			continue
		}
		fmt.Fprintf(&out, "{OSMID: %d, Highway: %q, Ref: %q, Name: %q, Lanes: %d, OneWay: %t, Points: []point{\n",
			way.ID, highway, way.Tags["ref"], way.Tags["name"], lanes(way.Tags["lanes"], highway), way.Tags["oneway"] != "no")
		for _, point := range way.Geometry {
			fmt.Fprintf(&out, "{Lat: %.7f, Lon: %.7f},\n", point.Lat, point.Lon)
		}
		out.WriteString("}},\n")
		count++
	}
	out.WriteString("}\n")
	if err := os.WriteFile("internal/locator/network_generated.go", []byte(out.String()), 0644); err != nil {
		panic(err)
	}
	fmt.Printf("embedded %d motorway and motorway_link ways\n", count)
}

func lanes(value, highway string) int {
	parsed, err := strconv.Atoi(value)
	if err == nil && parsed > 0 && parsed < 9 {
		return parsed
	}
	if highway == "motorway_link" {
		return 1
	}
	return 2
}
