// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export type {
    Coverage,
    LocalMap,
    MapPoint,
    NetworkHealth,
    OmapAttachment,
    OmapExportResult,
    OmapPointInput,
    OmapRangeInput,
    OmapRangeResult,
    Result,
    RoadFeature,
    RouteHealth
} from "./models.js";
