// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Coverage {
    "segmentId": string;
    "brigade": string;
    "segmentName": string;
    "code": string;
    "name": string;
    "start": string;
    "end": string;
    "lengthKm": string;
    "controlQty": number;
}

/**
 * LocalMap is a close, station-centred road scene rather than a route overview.
 */
export interface LocalMap {
    "result": Result;
    "centerLatitude": number;
    "centerLongitude": number;
    "rangeM": number;
    "roads": RoadFeature[] | null;
    "mainlineOffsetM": number;
    "mainlineMatched": boolean;
    "mainlineWayQty": number;
    "headingDegrees": number;
    "snapshot": string;
}

/**
 * MapPoint is a WGS-84 vertex from the embedded road geometry.
 */
export interface MapPoint {
    "latitude": number;
    "longitude": number;
}

/**
 * NetworkHealth describes the embedded public network snapshot and its
 * repeatable route-fit audit. It is intentionally data-oriented so future
 * imagery, patrol, and survey sources can be added without changing callers.
 */
export interface NetworkHealth {
    "snapshot": string;
    "roadWayQty": number;
    "rampWayQty": number;
    "vertexQty": number;
    "routeAudits": RouteHealth[] | null;
}

export interface OmapAttachment {
    "name": string;
    "path": string;
    "omapName"?: string;
    "size": number;
}

export interface OmapExportResult {
    "packagePath": string;
    "ovjsnPath": string;
    "ovkmlPath": string;
    "manifestPath": string;
    "targetFolder": string;
    "objectId": number;
    "attachmentQty": number;
    "omapAttachmentQty": number;
    "omapAttachmentDirectory"?: string;
    "attachments": OmapAttachment[] | null;
    "dataFile"?: string;
    "backupDirectory"?: string;
    "nativeImported": boolean;
    "result": Result;
}

/**
 * OmapPointInput describes one point to exchange with OMAP. Attachment paths
 * are local files selected by the native Windows file dialog.
 */
export interface OmapPointInput {
    "station": string;
    "brigade": string;
    "segmentId": string;
    "assetType": string;
    "name": string;
    "attachments": string[] | null;
    "outputDirectory": string;
    "syncToOmap": boolean;
}

/**
 * OmapRangeInput describes an attachment-free whole-kilometre import.
 * StartStation and EndStation accept values such as "1766" or "K1766".
 */
export interface OmapRangeInput {
    "route": string;
    "brigade": string;
    "segmentId": string;
    "startStation": string;
    "endStation": string;
    "name": string;
    "outputDirectory": string;
}

export interface OmapRangeResult {
    "targetFolder": string;
    "objectIds": number[] | null;
    "firstStation": string;
    "lastStation": string;
    "written": number;
    "skipped": number;
}

export interface Result {
    "input": string;
    "segmentId"?: string;
    "route": string;
    "routeName": string;
    "station": string;
    "meter": number;
    "latitude": number;
    "longitude": number;
    "coordinateSystem": string;
    "reference": string;
    "nearestControl": string;
    "controlDistanceM": number;
    "coverage": string;
    "verificationState": string;
}

/**
 * RoadFeature is one actual public road way near the resolved point. Main
 * carriageways and motorway_link geometries are retained separately.
 */
export interface RoadFeature {
    "osmId": number;
    "kind": string;
    "ref": string;
    "name": string;
    "lanes": number;
    "oneWay": boolean;
    "points": MapPoint[] | null;
}

/**
 * RouteHealth records the repeatable fit check between the calibrated station
 * path and the independently embedded local road-network ways.
 */
export interface RouteHealth {
    "code": string;
    "sampleQty": number;
    "controlQty": number;
    "mainlineWayQty": number;
    "maxMainlineOffsetM": number;
    "meanMainlineOffsetM": number;
}

/**
 * RouteSegment is the operator-facing jurisdiction catalog. Coordinates for
 * supplied control points are retained as anchors; the remaining path is
 * derived from the embedded public road snapshot and snapped to matching ways.
 */
export interface RouteSegment {
    "id": string;
    "brigade": string;
    "code": string;
    "name": string;
    "segmentName": string;
    "start": string;
    "end": string;
    "startMeter": number;
    "endMeter": number;
    "controlQty": number;
}
