// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as locator$0 from "./internal/locator/models.js";

export function ExportOmap(input: locator$0.OmapPointInput): $CancellablePromise<locator$0.OmapExportResult> {
    return $Call.ByID(310271424, input);
}

export function ExportOmapRange(input: locator$0.OmapRangeInput): $CancellablePromise<locator$0.OmapRangeResult> {
    return $Call.ByID(375290997, input);
}

export function GetCoverage(): $CancellablePromise<locator$0.Coverage[] | null> {
    return $Call.ByID(208512359);
}

export function GetNetworkHealth(): $CancellablePromise<locator$0.NetworkHealth> {
    return $Call.ByID(3328201531);
}

export function GetOmapExportDirectory(): $CancellablePromise<string> {
    return $Call.ByID(1237041721);
}

export function Locate(station: string): $CancellablePromise<locator$0.Result> {
    return $Call.ByID(2787902665, station);
}

export function LocateWithMap(station: string): $CancellablePromise<locator$0.LocalMap> {
    return $Call.ByID(729521609, station);
}

export function PickAttachments(): $CancellablePromise<string[] | null> {
    return $Call.ByID(596846036);
}

export function PickOmapDataDirectory(): $CancellablePromise<string> {
    return $Call.ByID(1843839430);
}
